name: TheDungeon
version: '${version}'
main: t.me.p1azmer.plugin.dungeons.DungeonPlugin
api-version: '1.17'
author: "plazmer"
description: "Dungeons - Automatic generation in any world"
folia-support: true
depend: [ PLAZMER-ENGINE ]
softdepend:
  - ProtectionBlocks
  - HolographicDisplays
  - FancyHolograms
  - DecentHolograms
  - WorldEdit
  - WorldGuard
  - ItemsAdder
  - MMOItems
  - GriefDefender
  - GriefPrevention
  - FastAsyncWorldEdit
  - PlaceholderAPI
  - KingdomsX
  - PartyAndFriends
  - Towny
  - Parties
  - Fabled